"""add pre registrations

Revision ID: 071aaf51348b
Revises: ebf97e030241
Create Date: 2026-02-16 19:27:41.106912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '071aaf51348b'
down_revision = 'ebf97e030241'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pre_registrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('iin', sa.String(length=20), nullable=False),
    sa.Column('education_level', sa.String(length=40), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('photo_path', sa.String(length=255), nullable=True),
    sa.Column('id_image_path', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pre_regs_iin_status', 'pre_registrations', ['iin', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pre_regs_iin_status', table_name='pre_registrations')
    op.drop_table('pre_registrations')
    # ### end Alembic commands ###
