"""add pre registration course level

Revision ID: 9218fee7a146
Revises: 071aaf51348b
Create Date: 2026-02-16 19:42:16.087949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9218fee7a146'
down_revision = '071aaf51348b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pre_registrations', sa.Column('course_level', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pre_registrations', 'course_level')
    # ### end Alembic commands ###
