"""add attendance qr tokens

Revision ID: ccf53edfcc24
Revises: f1a2c3d4e5f6
Create Date: 2026-02-18 13:22:11.462197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccf53edfcc24'
down_revision = 'f1a2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'attendance_qr_tokens',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('session_id', sa.Integer(), nullable=False),
        sa.Column('token', sa.String(length=64), nullable=False),
        sa.Column('expires_at', sa.DateTime(), nullable=False),
        sa.Column('created_by_user_id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id']),
        sa.ForeignKeyConstraint(['session_id'], ['sessions.id']),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_attendance_qr_session_expires', 'attendance_qr_tokens', ['session_id', 'expires_at'], unique=False)
    op.create_index(op.f('ix_attendance_qr_tokens_token'), 'attendance_qr_tokens', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attendance_qr_tokens_token'), table_name='attendance_qr_tokens')
    op.drop_index('ix_attendance_qr_session_expires', table_name='attendance_qr_tokens')
    op.drop_table('attendance_qr_tokens')
    # ### end Alembic commands ###
